### ISSUE TITLE
Incompatibility with SizeUp

### ISSUE THREAD

**Issue by TheLocehiliosan** [dexterleng/vimac-releases#17] opened 2019-10-23 17:26 UTC
I've noticed, when I start running vimac.app, the "Center" and "Full Screen" features of [SizeUp](http://www.irradiatedsoftware.com/sizeup/) stop working correctly (they resize the application in unexpected ways). I'm not sure what the actually incompatibility is, but that software also requires "accessibility" permissions.

I'm very interested in vimac's development, but I won't be able to use it if it interferes with SizeUp's operation.

**Comment by TheLocehiliosan** [comment] 2019-10-23 17:47
To help understand the issue, I've created this video.

https://imgur.com/a/UFAnLks

In the video, you can see SizeUp working correctly until at about 14 seconds in, where I activate the `CTRL-S` scroll, and then deactivate it. After that, SizeUp starts behaving strangely.

**Comment by dexterleng** [comment] 2019-10-24 13:40
It appears to be a problem with window managers in general.

**Comment by dexterleng** [comment] 2019-11-03 02:38
I've disabled Chromium support (hopefully temporarily) as it is the cause of this problem. Fixed in v0.3.1.

**Closed as completed by dexterleng** 2019-11-03 02:38 UTC
Labels: bug

**Comment by TheLocehiliosan** [comment] 2019-11-13 13:55
@dexterleng Thanks for this change... I does seem to solve the problem. 👍
